import os
# pyrefly: ignore [missing-import]
from dotenv import load_dotenv
# pyrefly: ignore [missing-import]
from google import genai

load_dotenv() 

class InsightsService:

 def __init__(self):
    self.api_key = os.getenv("GEMINI_API_KEY")

    if not self.api_key:
        raise ValueError(
            "Gemini API not found")
    
    self.client = genai.Client(
       api_key = self.api_key
    )

    self.model_name = "gemini-2.5-flash"


 def build_prompt(
      self,
      customer_data,
      churn_prediction,
      churn_probability,
      customer_segment,
      recommendation 
    ):
   
     prompt = f"""
     You are a Senior Business Analyst for an AI Customer Intelligence Platform
     The following prediction results have been generated by machine learning models.
     IMPORTANT:
     - Do NOT modify the churn prediction.
     - Do NOT modify the churn probability.
     - Do NOT modify the customer segment.
     - Do NOT invent any prediction values.
     - Your job is only to explain and enhance the results.

     Customer Profile


     Age: {customer_data.get("Age", "N/A")}
     Gender: {customer_data.get("Gender", "N/A")}
     Membership: {customer_data.get("Membership", "N/A")}

     Preferred Shopping Time: {customer_data.get("Preferred_Shopping_Time", "N/A")}
     Payment Method: {customer_data.get("Payment_Method", "N/A")}
     Total Orders: {customer_data.get("Total_Orders", 0)}

     Average Order Value: {customer_data.get("Average_Order_Value", 0)}
     Total Spend: {customer_data.get("Total_Spend", 0)}
     Days Since Last Purchase: {customer_data.get("Days_Since_Last_Purchase", 0)}
     Average Orders Per Month: {customer_data.get("Average_Orders_Per_Month", 0)}
     Wishlist Items: {customer_data.get("Wishlist_Items", 0)}
     Cart Abandonment Rate: {customer_data.get("Cart_Abandonment_Rate", 0)}
     Coupons Used: {customer_data.get("Coupons_Used", 0)}
     Return Rate: {customer_data.get("Return_Rate", 0)}
     App Sessions Per Month: {customer_data.get("App_Sessions_Per_Month", 0)}
     Average Session Duration: {customer_data.get("Average_Session_Duration", 0)}
     Customer Support Tickets: {customer_data.get("Customer_Support_Tickets", 0)}
     Product Categories Purchased: {customer_data.get("Product_Categories_Purchased", 0)}
    
     Machine Learning Results
     Churn Prediction: {churn_prediction}
     Churn Probability: {churn_probability:.2%}
     Customer Segment: {customer_segment}

     Business Recommendation:
     {recommendation}

     Your Task
     Provide a professional business explanation that includes:

     1. Why the customer is at this level of churn risk.
     2. What the assigned customer segment indicates.
     3. Why the business recommendation is appropriate.
     4. Minimun 2 additional retention strategies.
     5. Keep the response concise (150–200 words).
     6. Use professional, business-oriented language.
     7. Do not change or contradict the ML predictions.

     """

     return prompt
 
 def _get_insights(
       self,
       customer_data,
       churn_prediction,
       churn_probability,
       customer_segment,
       recommendation):
    
    prompt = self.build_prompt(
       customer_data,
       churn_prediction,
       churn_probability,
       customer_segment,
       recommendation
    )
    
    try:
       response = self.client.models.generate_content(
          model = self.model_name,
          contents = prompt
       )
       return response.text.strip()
    
    except Exception as e:
      print(f"Gemini Error: {e}")
    

    return (
            "AI-generated business insights are currently unavailable."
        )


insights_service = InsightsService ()